# Generated by Django 4.2 on 2023-04-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('married', 'Y'), ('not-married', 'N'), ('divorced', 'D')], default='not-married', max_length=50, null=True),
        ),
    ]
