# Generated by Django 4.1.7 on 2023-05-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eye',
            name='condition',
            field=models.IntegerField(choices=[(3, 'Normal'), (2, 'Glaucoma'), (1, 'Diabetic Retinopathy'), (0, 'Cataract')], default=3),
        ),
    ]
